[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.solana-mainnet]
protocol = "substreams"
shard = "primary"
provider = [
    { label = "substreams", details = { type = "substreams", url = "http://localhost:9000", token = "", features = [
        "compression",
        "filters",
    ], conn_pool_size = 1 } },
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = ["default"]